spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supercv_db_dev?serverTimezone=Asia/Shanghai&useUnicode=true
    username: username_dev
    password: password_dev
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始连接数
      initialSize: 2
      # 最小连接池数量
      minIdle: 3
      # 最大连接池数量
      maxActive: 10
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT version()
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

# 地址: /swagger-ui/index.html
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    display-request-duration: true
    groups-order: ASC
    operationsSorter: method
  cache:
    disabled: true

wxOpen:
  appID: [set_by_yourself]
  appSecret: set_by_yourself

aliyun:
  accessKeyId: set_by_yourself
  accessKeySecret: set_by_yourself

sms:
  sign_name: set_by_yourself
  template_code: set_by_yourself

tencent:
  secretId: set_by_yourself
  secretKey: set_by_yourself

captcha:
  captchaAppId: set_by_yourself
  appSecretKey: set_by_yourself