spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/supercv_db_test?serverTimezone=Asia/Shanghai&useUnicode=true
    username: test
    password: test_123